# Generated by Django 2.2.3 on 2019-08-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_posts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='file',
            field=models.FileField(blank=True, upload_to='post_docs'),
        ),
    ]
